### PR TITLE
Added links to rmate repo and usage instrcutions

### PR DESCRIPTION
**Pull request by drevicko**

### CODE REVIEW

**Comment by KES777** [comment]
You provide wrong usage description. `rsub` is not required to be installed on local machine.

**Comment by KES777** [comment]
You provide wrong usage description. `rsub` is not required to be installed on local machine

**Comment by drevicko** [comment]
I'm confused. Do you mean that rsub should be installed into SublimeText on the local machine (as opposed to "on your local machine"?

**Comment by KES777** [comment]
Oh, sorry, I mixed up repos. I delete comment, to not confuse others

**Pull request merged**
